# Generated by Django 4.2.7 on 2023-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post'),
        ('main_app', '0004_profile_date_modified'),
    ]

    operations = [
    ]
