# Generated by Django 4.2.7 on 2023-11-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_attachment_post_attachments_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
